/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  DeleteSettingsRecordsId404,
  GetSettingsRecords200,
  GetSettingsRecordsId200,
  GetSettingsRecordsId404,
  GetSettingsRecordsParams,
  GetSettingsSuggestions200,
  PostSettingsRecords201,
  PostSettingsRecordsBody,
  PutSettingsRecordsId200,
  PutSettingsRecordsId404,
  PutSettingsRecordsIdBody,
} from "../../schemas";
import getSettingsRecordsMutator from "../../mutator";
import postSettingsRecordsMutator from "../../mutator";
import getSettingsRecordsIdMutator from "../../mutator";
import putSettingsRecordsIdMutator from "../../mutator";
import deleteSettingsRecordsIdMutator from "../../mutator";
import getSettingsSuggestionsMutator from "../../mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * ユーザーの設定記録一覧を取得します
 * @summary 設定記録一覧取得
 */
export const getSettingsRecords = (
  params?: GetSettingsRecordsParams,
  options?: SecondParameter<typeof getSettingsRecordsMutator>,
  signal?: AbortSignal,
) => {
  return getSettingsRecordsMutator<GetSettingsRecords200>(
    { url: `/settings/records`, method: "GET", params, signal },
    options,
  );
};

export const getGetSettingsRecordsQueryKey = (
  params?: GetSettingsRecordsParams,
) => {
  return [`/settings/records`, ...(params ? [params] : [])] as const;
};

export const getGetSettingsRecordsInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsRecords>>,
  TError = unknown,
>(
  params?: GetSettingsRecordsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsRecordsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsRecords>>
  > = ({ signal }) => getSettingsRecords(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSettingsRecords>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsRecordsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsRecords>>
>;
export type GetSettingsRecordsInfiniteQueryError = unknown;

/**
 * @summary 設定記録一覧取得
 */
export const useGetSettingsRecordsInfinite = <
  TData = Awaited<ReturnType<typeof getSettingsRecords>>,
  TError = unknown,
>(
  params?: GetSettingsRecordsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsRecordsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetSettingsRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsRecords>>,
  TError = unknown,
>(
  params?: GetSettingsRecordsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsRecordsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsRecords>>
  > = ({ signal }) => getSettingsRecords(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsRecords>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsRecords>>
>;
export type GetSettingsRecordsQueryError = unknown;

/**
 * @summary 設定記録一覧取得
 */
export const useGetSettingsRecords = <
  TData = Awaited<ReturnType<typeof getSettingsRecords>>,
  TError = unknown,
>(
  params?: GetSettingsRecordsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsRecordsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 新しい設定記録を作成します
 * @summary 設定記録作成
 */
export const postSettingsRecords = (
  postSettingsRecordsBody: PostSettingsRecordsBody,
  options?: SecondParameter<typeof postSettingsRecordsMutator>,
) => {
  return postSettingsRecordsMutator<PostSettingsRecords201>(
    {
      url: `/settings/records`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postSettingsRecordsBody,
    },
    options,
  );
};

export const getPostSettingsRecordsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSettingsRecords>>,
    TError,
    { data: PostSettingsRecordsBody },
    TContext
  >;
  request?: SecondParameter<typeof postSettingsRecordsMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSettingsRecords>>,
  TError,
  { data: PostSettingsRecordsBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSettingsRecords>>,
    { data: PostSettingsRecordsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postSettingsRecords(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostSettingsRecordsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSettingsRecords>>
>;
export type PostSettingsRecordsMutationBody = PostSettingsRecordsBody;
export type PostSettingsRecordsMutationError = unknown;

/**
 * @summary 設定記録作成
 */
export const usePostSettingsRecords = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSettingsRecords>>,
    TError,
    { data: PostSettingsRecordsBody },
    TContext
  >;
  request?: SecondParameter<typeof postSettingsRecordsMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postSettingsRecords>>,
  TError,
  { data: PostSettingsRecordsBody },
  TContext
> => {
  const mutationOptions = getPostSettingsRecordsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 指定された設定記録の詳細を取得します
 * @summary 設定記録詳細取得
 */
export const getSettingsRecordsId = (
  id: string,
  options?: SecondParameter<typeof getSettingsRecordsIdMutator>,
  signal?: AbortSignal,
) => {
  return getSettingsRecordsIdMutator<GetSettingsRecordsId200>(
    { url: `/settings/records/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetSettingsRecordsIdQueryKey = (id: string) => {
  return [`/settings/records/${id}`] as const;
};

export const getGetSettingsRecordsIdInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsRecordsId>>,
  TError = GetSettingsRecordsId404,
>(
  id: string,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecordsId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsIdMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsRecordsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsRecordsId>>
  > = ({ signal }) => getSettingsRecordsId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSettingsRecordsId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsRecordsIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsRecordsId>>
>;
export type GetSettingsRecordsIdInfiniteQueryError = GetSettingsRecordsId404;

/**
 * @summary 設定記録詳細取得
 */
export const useGetSettingsRecordsIdInfinite = <
  TData = Awaited<ReturnType<typeof getSettingsRecordsId>>,
  TError = GetSettingsRecordsId404,
>(
  id: string,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecordsId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsIdMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsRecordsIdInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetSettingsRecordsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsRecordsId>>,
  TError = GetSettingsRecordsId404,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecordsId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsIdMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsRecordsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsRecordsId>>
  > = ({ signal }) => getSettingsRecordsId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsRecordsId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsRecordsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsRecordsId>>
>;
export type GetSettingsRecordsIdQueryError = GetSettingsRecordsId404;

/**
 * @summary 設定記録詳細取得
 */
export const useGetSettingsRecordsId = <
  TData = Awaited<ReturnType<typeof getSettingsRecordsId>>,
  TError = GetSettingsRecordsId404,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSettingsRecordsId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getSettingsRecordsIdMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsRecordsIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 指定された設定記録を更新します
 * @summary 設定記録更新
 */
export const putSettingsRecordsId = (
  id: string,
  putSettingsRecordsIdBody: PutSettingsRecordsIdBody,
  options?: SecondParameter<typeof putSettingsRecordsIdMutator>,
) => {
  return putSettingsRecordsIdMutator<PutSettingsRecordsId200>(
    {
      url: `/settings/records/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: putSettingsRecordsIdBody,
    },
    options,
  );
};

export const getPutSettingsRecordsIdMutationOptions = <
  TError = PutSettingsRecordsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putSettingsRecordsId>>,
    TError,
    { id: string; data: PutSettingsRecordsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof putSettingsRecordsIdMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putSettingsRecordsId>>,
  TError,
  { id: string; data: PutSettingsRecordsIdBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putSettingsRecordsId>>,
    { id: string; data: PutSettingsRecordsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putSettingsRecordsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutSettingsRecordsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putSettingsRecordsId>>
>;
export type PutSettingsRecordsIdMutationBody = PutSettingsRecordsIdBody;
export type PutSettingsRecordsIdMutationError = PutSettingsRecordsId404;

/**
 * @summary 設定記録更新
 */
export const usePutSettingsRecordsId = <
  TError = PutSettingsRecordsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putSettingsRecordsId>>,
    TError,
    { id: string; data: PutSettingsRecordsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof putSettingsRecordsIdMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putSettingsRecordsId>>,
  TError,
  { id: string; data: PutSettingsRecordsIdBody },
  TContext
> => {
  const mutationOptions = getPutSettingsRecordsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 指定された設定記録を削除します
 * @summary 設定記録削除
 */
export const deleteSettingsRecordsId = (
  id: string,
  options?: SecondParameter<typeof deleteSettingsRecordsIdMutator>,
) => {
  return deleteSettingsRecordsIdMutator<void>(
    { url: `/settings/records/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteSettingsRecordsIdMutationOptions = <
  TError = DeleteSettingsRecordsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSettingsRecordsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof deleteSettingsRecordsIdMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSettingsRecordsId>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSettingsRecordsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteSettingsRecordsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSettingsRecordsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSettingsRecordsId>>
>;

export type DeleteSettingsRecordsIdMutationError = DeleteSettingsRecordsId404;

/**
 * @summary 設定記録削除
 */
export const useDeleteSettingsRecordsId = <
  TError = DeleteSettingsRecordsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSettingsRecordsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof deleteSettingsRecordsIdMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteSettingsRecordsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteSettingsRecordsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * デバイス名などの入力サジェストを取得します
 * @summary 設定入力サジェスト取得
 */
export const getSettingsSuggestions = (
  options?: SecondParameter<typeof getSettingsSuggestionsMutator>,
  signal?: AbortSignal,
) => {
  return getSettingsSuggestionsMutator<GetSettingsSuggestions200>(
    { url: `/settings/suggestions`, method: "GET", signal },
    options,
  );
};

export const getGetSettingsSuggestionsQueryKey = () => {
  return [`/settings/suggestions`] as const;
};

export const getGetSettingsSuggestionsInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getSettingsSuggestionsMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsSuggestionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsSuggestions>>
  > = ({ signal }) => getSettingsSuggestions(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsSuggestionsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsSuggestions>>
>;
export type GetSettingsSuggestionsInfiniteQueryError = unknown;

/**
 * @summary 設定入力サジェスト取得
 */
export const useGetSettingsSuggestionsInfinite = <
  TData = Awaited<ReturnType<typeof getSettingsSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getSettingsSuggestionsMutator>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsSuggestionsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetSettingsSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getSettingsSuggestionsMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsSuggestionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsSuggestions>>
  > = ({ signal }) => getSettingsSuggestions(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSettingsSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsSuggestions>>
>;
export type GetSettingsSuggestionsQueryError = unknown;

/**
 * @summary 設定入力サジェスト取得
 */
export const useGetSettingsSuggestions = <
  TData = Awaited<ReturnType<typeof getSettingsSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsSuggestions>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getSettingsSuggestionsMutator>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetSettingsSuggestionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
