/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetMatchData200,
  GetMatchDataParams,
  GetMatchDataSummary200,
  GetMatchDataSummaryParams,
  PostMatchDataGenerateMock200,
  PostMatchDataGenerateMock403,
  PostMatchDataGenerateMockBody,
  PostMatchDataSync202,
  PostMatchDataSync400,
  PostMatchDataSync429,
  PostMatchDataSyncBody,
} from "../../schemas";
import getMatchDataMutator from "../../mutator";
import postMatchDataSyncMutator from "../../mutator";
import postMatchDataGenerateMockMutator from "../../mutator";
import getMatchDataSummaryMutator from "../../mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * ユーザーの試合データ一覧を取得します
 * @summary 試合データ取得
 */
export const getMatchData = (
  params?: GetMatchDataParams,
  options?: SecondParameter<typeof getMatchDataMutator>,
  signal?: AbortSignal,
) => {
  return getMatchDataMutator<GetMatchData200>(
    { url: `/match-data/`, method: "GET", params, signal },
    options,
  );
};

export const getGetMatchDataQueryKey = (params?: GetMatchDataParams) => {
  return [`/match-data/`, ...(params ? [params] : [])] as const;
};

export const getGetMatchDataInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = unknown,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMatchDataQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchData>>> = ({
    signal,
  }) => getMatchData(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getMatchData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchData>>
>;
export type GetMatchDataInfiniteQueryError = unknown;

/**
 * @summary 試合データ取得
 */
export const useGetMatchDataInfinite = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = unknown,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetMatchDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = unknown,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMatchDataQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatchData>>> = ({
    signal,
  }) => getMatchData(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMatchData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchData>>
>;
export type GetMatchDataQueryError = unknown;

/**
 * @summary 試合データ取得
 */
export const useGetMatchData = <
  TData = Awaited<ReturnType<typeof getMatchData>>,
  TError = unknown,
>(
  params?: GetMatchDataParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchData>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Riot APIから最新の試合データを取得します
 * @summary 試合データ手動同期
 */
export const postMatchDataSync = (
  postMatchDataSyncBody: PostMatchDataSyncBody,
  options?: SecondParameter<typeof postMatchDataSyncMutator>,
) => {
  return postMatchDataSyncMutator<PostMatchDataSync202>(
    {
      url: `/match-data/sync`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postMatchDataSyncBody,
    },
    options,
  );
};

export const getPostMatchDataSyncMutationOptions = <
  TError = PostMatchDataSync400 | PostMatchDataSync429,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    TError,
    { data: PostMatchDataSyncBody },
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataSyncMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMatchDataSync>>,
  TError,
  { data: PostMatchDataSyncBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    { data: PostMatchDataSyncBody }
  > = (props) => {
    const { data } = props ?? {};

    return postMatchDataSync(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMatchDataSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMatchDataSync>>
>;
export type PostMatchDataSyncMutationBody = PostMatchDataSyncBody;
export type PostMatchDataSyncMutationError =
  | PostMatchDataSync400
  | PostMatchDataSync429;

/**
 * @summary 試合データ手動同期
 */
export const usePostMatchDataSync = <
  TError = PostMatchDataSync400 | PostMatchDataSync429,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataSync>>,
    TError,
    { data: PostMatchDataSyncBody },
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataSyncMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postMatchDataSync>>,
  TError,
  { data: PostMatchDataSyncBody },
  TContext
> => {
  const mutationOptions = getPostMatchDataSyncMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 開発用のモック試合データを生成します
 * @summary モック試合データ生成
 */
export const postMatchDataGenerateMock = (
  postMatchDataGenerateMockBody: PostMatchDataGenerateMockBody,
  options?: SecondParameter<typeof postMatchDataGenerateMockMutator>,
) => {
  return postMatchDataGenerateMockMutator<PostMatchDataGenerateMock200>(
    {
      url: `/match-data/generate-mock`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postMatchDataGenerateMockBody,
    },
    options,
  );
};

export const getPostMatchDataGenerateMockMutationOptions = <
  TError = PostMatchDataGenerateMock403,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataGenerateMock>>,
    TError,
    { data: PostMatchDataGenerateMockBody },
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataGenerateMockMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMatchDataGenerateMock>>,
  TError,
  { data: PostMatchDataGenerateMockBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMatchDataGenerateMock>>,
    { data: PostMatchDataGenerateMockBody }
  > = (props) => {
    const { data } = props ?? {};

    return postMatchDataGenerateMock(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMatchDataGenerateMockMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMatchDataGenerateMock>>
>;
export type PostMatchDataGenerateMockMutationBody =
  PostMatchDataGenerateMockBody;
export type PostMatchDataGenerateMockMutationError =
  PostMatchDataGenerateMock403;

/**
 * @summary モック試合データ生成
 */
export const usePostMatchDataGenerateMock = <
  TError = PostMatchDataGenerateMock403,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMatchDataGenerateMock>>,
    TError,
    { data: PostMatchDataGenerateMockBody },
    TContext
  >;
  request?: SecondParameter<typeof postMatchDataGenerateMockMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postMatchDataGenerateMock>>,
  TError,
  { data: PostMatchDataGenerateMockBody },
  TContext
> => {
  const mutationOptions = getPostMatchDataGenerateMockMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 試合データの統計サマリーを取得します
 * @summary 試合データサマリー
 */
export const getMatchDataSummary = (
  params?: GetMatchDataSummaryParams,
  options?: SecondParameter<typeof getMatchDataSummaryMutator>,
  signal?: AbortSignal,
) => {
  return getMatchDataSummaryMutator<GetMatchDataSummary200>(
    { url: `/match-data/summary`, method: "GET", params, signal },
    options,
  );
};

export const getGetMatchDataSummaryQueryKey = (
  params?: GetMatchDataSummaryParams,
) => {
  return [`/match-data/summary`, ...(params ? [params] : [])] as const;
};

export const getGetMatchDataSummaryInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchDataSummary>>,
  TError = unknown,
>(
  params?: GetMatchDataSummaryParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchDataSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataSummaryMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMatchDataSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMatchDataSummary>>
  > = ({ signal }) => getMatchDataSummary(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getMatchDataSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataSummaryInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchDataSummary>>
>;
export type GetMatchDataSummaryInfiniteQueryError = unknown;

/**
 * @summary 試合データサマリー
 */
export const useGetMatchDataSummaryInfinite = <
  TData = Awaited<ReturnType<typeof getMatchDataSummary>>,
  TError = unknown,
>(
  params?: GetMatchDataSummaryParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getMatchDataSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataSummaryMutator>;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataSummaryInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetMatchDataSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getMatchDataSummary>>,
  TError = unknown,
>(
  params?: GetMatchDataSummaryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchDataSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataSummaryMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMatchDataSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMatchDataSummary>>
  > = ({ signal }) => getMatchDataSummary(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMatchDataSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMatchDataSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMatchDataSummary>>
>;
export type GetMatchDataSummaryQueryError = unknown;

/**
 * @summary 試合データサマリー
 */
export const useGetMatchDataSummary = <
  TData = Awaited<ReturnType<typeof getMatchDataSummary>>,
  TError = unknown,
>(
  params?: GetMatchDataSummaryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMatchDataSummary>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof getMatchDataSummaryMutator>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMatchDataSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
