/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAuthMe200,
  GetAuthRiotLogin200,
  PostAuthRefresh200,
  PostAuthRiotCallback200,
  PostAuthRiotCallback400,
  PostAuthRiotCallbackBody,
} from "../../schemas";
import getAuthRiotLoginMutator from "../../mutator";
import postAuthRiotCallbackMutator from "../../mutator";
import postAuthRefreshMutator from "../../mutator";
import getAuthMeMutator from "../../mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Riot Gamesアカウントでの認証を開始します（開発環境ではモック認証）
 * @summary Riot OAuth認証開始
 */
export const getAuthRiotLogin = (
  options?: SecondParameter<typeof getAuthRiotLoginMutator>,
  signal?: AbortSignal,
) => {
  return getAuthRiotLoginMutator<GetAuthRiotLogin200>(
    { url: `/auth/riot/login`, method: "GET", signal },
    options,
  );
};

export const getGetAuthRiotLoginQueryKey = () => {
  return [`/auth/riot/login`] as const;
};

export const getGetAuthRiotLoginInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthRiotLogin>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthRiotLoginMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthRiotLoginQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAuthRiotLogin>>
  > = ({ signal }) => getAuthRiotLogin(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuthRiotLoginInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthRiotLogin>>
>;
export type GetAuthRiotLoginInfiniteQueryError = unknown;

/**
 * @summary Riot OAuth認証開始
 */
export const useGetAuthRiotLoginInfinite = <
  TData = Awaited<ReturnType<typeof getAuthRiotLogin>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthRiotLoginMutator>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthRiotLoginInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetAuthRiotLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthRiotLogin>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthRiotLoginMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthRiotLoginQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAuthRiotLogin>>
  > = ({ signal }) => getAuthRiotLogin(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuthRiotLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthRiotLogin>>
>;
export type GetAuthRiotLoginQueryError = unknown;

/**
 * @summary Riot OAuth認証開始
 */
export const useGetAuthRiotLogin = <
  TData = Awaited<ReturnType<typeof getAuthRiotLogin>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAuthRiotLogin>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthRiotLoginMutator>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthRiotLoginQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * Riot認証サーバーからのコールバックを処理します
 * @summary Riot OAuth認証コールバック
 */
export const postAuthRiotCallback = (
  postAuthRiotCallbackBody: PostAuthRiotCallbackBody,
  options?: SecondParameter<typeof postAuthRiotCallbackMutator>,
) => {
  return postAuthRiotCallbackMutator<PostAuthRiotCallback200>(
    {
      url: `/auth/riot/callback`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthRiotCallbackBody,
    },
    options,
  );
};

export const getPostAuthRiotCallbackMutationOptions = <
  TError = PostAuthRiotCallback400,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRiotCallback>>,
    TError,
    { data: PostAuthRiotCallbackBody },
    TContext
  >;
  request?: SecondParameter<typeof postAuthRiotCallbackMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRiotCallback>>,
  TError,
  { data: PostAuthRiotCallbackBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRiotCallback>>,
    { data: PostAuthRiotCallbackBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRiotCallback(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRiotCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRiotCallback>>
>;
export type PostAuthRiotCallbackMutationBody = PostAuthRiotCallbackBody;
export type PostAuthRiotCallbackMutationError = PostAuthRiotCallback400;

/**
 * @summary Riot OAuth認証コールバック
 */
export const usePostAuthRiotCallback = <
  TError = PostAuthRiotCallback400,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRiotCallback>>,
    TError,
    { data: PostAuthRiotCallbackBody },
    TContext
  >;
  request?: SecondParameter<typeof postAuthRiotCallbackMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRiotCallback>>,
  TError,
  { data: PostAuthRiotCallbackBody },
  TContext
> => {
  const mutationOptions = getPostAuthRiotCallbackMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * JWTトークンを新しいものに更新します
 * @summary JWTトークンリフレッシュ
 */
export const postAuthRefresh = (
  options?: SecondParameter<typeof postAuthRefreshMutator>,
) => {
  return postAuthRefreshMutator<PostAuthRefresh200>(
    { url: `/auth/refresh`, method: "POST" },
    options,
  );
};

export const getPostAuthRefreshMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof postAuthRefreshMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    void
  > = () => {
    return postAuthRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefresh>>
>;

export type PostAuthRefreshMutationError = unknown;

/**
 * @summary JWTトークンリフレッシュ
 */
export const usePostAuthRefresh = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof postAuthRefreshMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 認証済みユーザーの情報を取得します
 * @summary ユーザー情報取得
 */
export const getAuthMe = (
  options?: SecondParameter<typeof getAuthMeMutator>,
  signal?: AbortSignal,
) => {
  return getAuthMeMutator<GetAuthMe200>(
    { url: `/auth/me`, method: "GET", signal },
    options,
  );
};

export const getGetAuthMeQueryKey = () => {
  return [`/auth/me`] as const;
};

export const getGetAuthMeInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthMeMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({
    signal,
  }) => getAuthMe(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAuthMeInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthMe>>
>;
export type GetAuthMeInfiniteQueryError = unknown;

/**
 * @summary ユーザー情報取得
 */
export const useGetAuthMeInfinite = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getAuthMeMutator>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthMeInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>;
  request?: SecondParameter<typeof getAuthMeMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({
    signal,
  }) => getAuthMe(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetAuthMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthMe>>
>;
export type GetAuthMeQueryError = unknown;

/**
 * @summary ユーザー情報取得
 */
export const useGetAuthMe = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>;
  request?: SecondParameter<typeof getAuthMeMutator>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAuthMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
