/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * SensiLog API
 * VALORANT感度・設定管理API
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  DeleteRiotUnlinkAccount200,
  GetRiotLinkStatus200,
  PostRiotLinkAccount200,
  PostRiotLinkAccount400,
  PostRiotLinkAccount404,
  PostRiotLinkAccountBody,
  PostRiotSearchPlayer200,
  PostRiotSearchPlayer400,
  PostRiotSearchPlayer404,
  PostRiotSearchPlayerBody,
} from "../../schemas";
import postRiotSearchPlayerMutator from "../../mutator";
import postRiotLinkAccountMutator from "../../mutator";
import deleteRiotUnlinkAccountMutator from "../../mutator";
import getRiotLinkStatusMutator from "../../mutator";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * ゲーム名とタグラインでプレイヤーを検索します
 * @summary プレイヤー検索
 */
export const postRiotSearchPlayer = (
  postRiotSearchPlayerBody: PostRiotSearchPlayerBody,
  options?: SecondParameter<typeof postRiotSearchPlayerMutator>,
) => {
  return postRiotSearchPlayerMutator<PostRiotSearchPlayer200>(
    {
      url: `/riot/search-player`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postRiotSearchPlayerBody,
    },
    options,
  );
};

export const getPostRiotSearchPlayerMutationOptions = <
  TError = PostRiotSearchPlayer400 | PostRiotSearchPlayer404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRiotSearchPlayer>>,
    TError,
    { data: PostRiotSearchPlayerBody },
    TContext
  >;
  request?: SecondParameter<typeof postRiotSearchPlayerMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRiotSearchPlayer>>,
  TError,
  { data: PostRiotSearchPlayerBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRiotSearchPlayer>>,
    { data: PostRiotSearchPlayerBody }
  > = (props) => {
    const { data } = props ?? {};

    return postRiotSearchPlayer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRiotSearchPlayerMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRiotSearchPlayer>>
>;
export type PostRiotSearchPlayerMutationBody = PostRiotSearchPlayerBody;
export type PostRiotSearchPlayerMutationError =
  | PostRiotSearchPlayer400
  | PostRiotSearchPlayer404;

/**
 * @summary プレイヤー検索
 */
export const usePostRiotSearchPlayer = <
  TError = PostRiotSearchPlayer400 | PostRiotSearchPlayer404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRiotSearchPlayer>>,
    TError,
    { data: PostRiotSearchPlayerBody },
    TContext
  >;
  request?: SecondParameter<typeof postRiotSearchPlayerMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRiotSearchPlayer>>,
  TError,
  { data: PostRiotSearchPlayerBody },
  TContext
> => {
  const mutationOptions = getPostRiotSearchPlayerMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * ユーザーとRiotアカウントを連携します
 * @summary Riotアカウント連携
 */
export const postRiotLinkAccount = (
  postRiotLinkAccountBody: PostRiotLinkAccountBody,
  options?: SecondParameter<typeof postRiotLinkAccountMutator>,
) => {
  return postRiotLinkAccountMutator<PostRiotLinkAccount200>(
    {
      url: `/riot/link-account`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postRiotLinkAccountBody,
    },
    options,
  );
};

export const getPostRiotLinkAccountMutationOptions = <
  TError = PostRiotLinkAccount400 | PostRiotLinkAccount404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRiotLinkAccount>>,
    TError,
    { data: PostRiotLinkAccountBody },
    TContext
  >;
  request?: SecondParameter<typeof postRiotLinkAccountMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRiotLinkAccount>>,
  TError,
  { data: PostRiotLinkAccountBody },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRiotLinkAccount>>,
    { data: PostRiotLinkAccountBody }
  > = (props) => {
    const { data } = props ?? {};

    return postRiotLinkAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRiotLinkAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRiotLinkAccount>>
>;
export type PostRiotLinkAccountMutationBody = PostRiotLinkAccountBody;
export type PostRiotLinkAccountMutationError =
  | PostRiotLinkAccount400
  | PostRiotLinkAccount404;

/**
 * @summary Riotアカウント連携
 */
export const usePostRiotLinkAccount = <
  TError = PostRiotLinkAccount400 | PostRiotLinkAccount404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRiotLinkAccount>>,
    TError,
    { data: PostRiotLinkAccountBody },
    TContext
  >;
  request?: SecondParameter<typeof postRiotLinkAccountMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postRiotLinkAccount>>,
  TError,
  { data: PostRiotLinkAccountBody },
  TContext
> => {
  const mutationOptions = getPostRiotLinkAccountMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Riotアカウントの連携を解除します
 * @summary Riotアカウント連携解除
 */
export const deleteRiotUnlinkAccount = (
  options?: SecondParameter<typeof deleteRiotUnlinkAccountMutator>,
) => {
  return deleteRiotUnlinkAccountMutator<DeleteRiotUnlinkAccount200>(
    { url: `/riot/unlink-account`, method: "DELETE" },
    options,
  );
};

export const getDeleteRiotUnlinkAccountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof deleteRiotUnlinkAccountMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>,
    void
  > = () => {
    return deleteRiotUnlinkAccount(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRiotUnlinkAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>
>;

export type DeleteRiotUnlinkAccountMutationError = unknown;

/**
 * @summary Riotアカウント連携解除
 */
export const useDeleteRiotUnlinkAccount = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof deleteRiotUnlinkAccountMutator>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteRiotUnlinkAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDeleteRiotUnlinkAccountMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Riotアカウントの連携状態を確認します
 * @summary Riotアカウント連携状態確認
 */
export const getRiotLinkStatus = (
  options?: SecondParameter<typeof getRiotLinkStatusMutator>,
  signal?: AbortSignal,
) => {
  return getRiotLinkStatusMutator<GetRiotLinkStatus200>(
    { url: `/riot/link-status`, method: "GET", signal },
    options,
  );
};

export const getGetRiotLinkStatusQueryKey = () => {
  return [`/riot/link-status`] as const;
};

export const getGetRiotLinkStatusInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof getRiotLinkStatus>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getRiotLinkStatusMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRiotLinkStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRiotLinkStatus>>
  > = ({ signal }) => getRiotLinkStatus(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRiotLinkStatusInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRiotLinkStatus>>
>;
export type GetRiotLinkStatusInfiniteQueryError = unknown;

/**
 * @summary Riotアカウント連携状態確認
 */
export const useGetRiotLinkStatusInfinite = <
  TData = Awaited<ReturnType<typeof getRiotLinkStatus>>,
  TError = unknown,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getRiotLinkStatusMutator>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRiotLinkStatusInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetRiotLinkStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getRiotLinkStatus>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getRiotLinkStatusMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRiotLinkStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRiotLinkStatus>>
  > = ({ signal }) => getRiotLinkStatus(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    retry: 1,
    refetchOnWindowFocus: false,
    staleTime: 120000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRiotLinkStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRiotLinkStatus>>
>;
export type GetRiotLinkStatusQueryError = unknown;

/**
 * @summary Riotアカウント連携状態確認
 */
export const useGetRiotLinkStatus = <
  TData = Awaited<ReturnType<typeof getRiotLinkStatus>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRiotLinkStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof getRiotLinkStatusMutator>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetRiotLinkStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
